---
title: "Tips to Upgrade Linux Server (LTS)"
output: html_document
author: Ali Altıntaş
date: 14.07.2020
---

This is a basic guideline on how to upgrade Linux Server LTS versions. Maybe, I should call it "what I learned from my mistakes" while upgrading from Linux Server 14.04 (LTS) to 20.04 (LTS).


## Remember to:

1. You need to upgrade sequentially across the versions: 14.04 (LTS) > 16.04 (LTS) >  18.04 (LTS) > 20.04 (LTS)
2. After each upgrade, you need to make sure that all libraries/packages are up to date. Otherwise, upgrade procedure will not start or will fail.
3. Every upgrade procedure is almost identical and following the tips below will save tremendous amount of time.

## Tips

1. Update & upgrade the packages

```
sudo apt update && sudo apt upgrade
```
**update**  is used to resynchronize the package index files from their sources

**upgrade** is used to install the newest versions of all packages currently installed on the system from the sources enumerated in /etc/apt/sources.list

2. (Optional) Remove the unnecessary dependencies
```
sudo apt autoremove
```

3. Download and install packages with `dist-upgrade`
```
sudo apt-get dist-upgrade
```

**dist-upgrade** in addition to performing the function of upgrade, also intelligently handles changing dependencies with new versions

4. Repeat step 1-3 until you have a message as follows:
```
$ 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

5. If you happen to end up with some "(...) N not upgraded" (N: integer > 1), detect which library those are and install manually. For example, I had a problem with `texlive-latex-extra-doc` and here is how I solved it:
```
wget http://dk.archive.ubuntu.com/ubuntu/pool/main/t/texlive-extra/texlive-latex-extra-doc_2015.20160320-1_all.deb
sudo dpkg --force-all -i texlive-latex-extra-doc_2015.20160320-1_all.deb
```

After manual installation: repeat step 1-4:
```
sudo apt update && sudo apt upgrade
sudo apt autoremove
sudo apt-get dist-upgrade
```

## Minor issues
After upgrading from 14.04 to 16.04, you might have network problems. Apparently it is a well-known issue and brave souls had found solutions to this [click here](https://askubuntu.com/questions/767574/no-network-after-upgrade-to-16-04).
